name: terraform infrastructure on Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-workflow:
    runs-on: ubuntu-latest
    env: # Available to all steps in this job
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Installing Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply 
        if: github.event_name == 'push'  #Only deploys on merge to main!
        run: terraform apply -auto-approve